import { Head } from "next/head";
const SectionWrapper = (Component, headerText) =>
  function HOC() {
    return (
      <div className="container mt-50">
        <Head>
          <title>{headerText} - Online Learning Platform</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Component />
      </div>
    );
  };

export default SectionWrapper;
